### ISSUE TITLE
Status and conflict with now-rust

### ISSUE THREAD

**Issue by mike-engel** [gogenhub/vercel-rust#1]
Hi @gogenhub. I'm the maintainer of what used to be called [now-rust](https://github.com/mike-engel/vercel-rust). Recently, however, I finally got around to changing the name to `vercel-rust`. When I went to publish the new package to npm, however, I found that this package already exists.

Is this project actively maintained?

If yes, I think we should combine our projects and have a single place people can go to deploy rust to vercel.

If no, would you be open to letting me have ownership of the [`vercel-rust`](https://www.npmjs.com/package/vercel-rust) package on npm?

**Comment by filiplazovic** [comment]
Hey @mike-engel,

I think we want to stay separate project for now, but I will grant you the package name.
I will process this over the weekend.

**Comment by filiplazovic** [comment]
@mike-engel Invited you to the `vercel-rust` package on npm, let me know if everything is ok so I can remove myself

**Comment by mike-engel** [comment]
@filiplazovic I really appreciate it. I just published my version of `vercel-rust` to npm successfully. In the future, I'm more than happy to collaborate or merge projects 😄
